version: '3.8'

services:
  mysql:
    image: mysql:8.0.42-debian
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopapp
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shop-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  shop-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DBMS_CONNECTION: jdbc:mysql://mysql:3306/shopapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - shop-app-network
    restart: "no"

networks:
  shop-app-network:
    driver: bridge

volumes:
  mysql-data: